import { describe, expect, it } from 'vitest';
import type { Inventory } from '@/types';
import { validateParams } from '@/lib/interpreter';
import { manifests } from '@/data/manifests';
import {
  blockExample,
  buildProvisionOperation,
  createdTypeOf,
  describeProvisionRequest,
  groupProviderServices,
  isSchemaProvisionRequest,
  manifestCreateOpsByType,
  paramsFor,
  provisionOperationId,
  provisionRequestTitle,
  provisionResourceType,
  type CatalogIndex,
  type CatalogResource,
  type CatalogServiceChunk,
} from '@/lib/providerCatalog';
import { buildRequestDraft } from '@/lib/interpreter';
import { getCurrentUser } from '@/lib/session';
import acrChunk from '@/data/provider-catalog-azure/services/acr.json';

const EMPTY_INVENTORY: Inventory = { generatedAt: null, resources: [] };

/** A compact resource as the generator emits it (SQS-queue-like). */
const RES: CatalogResource = {
  attrs: [
    { n: 'queue_name', t: 'string', r: 1 },
    { n: 'delay_seconds', t: 'number' },
    { n: 'fifo_queue', t: 'bool' },
    { n: 'master_password', t: 'string', s: 1 },
    { n: 'subnet_ids', t: 'list' },
    { n: 'tags', t: 'map' },
    { n: 'policy_document', t: 'json' },
  ],
  blocks: [
    {
      n: 'encryption',
      m: 'single',
      attrs: [{ n: 'kms_key_id', t: 'string' }],
      blocks: [],
    },
    {
      n: 'rule',
      m: 'list',
      min: 1,
      attrs: [{ n: 'action', t: 'string', r: 1 }, { n: 'priority', t: 'number' }],
      blocks: [],
    },
  ],
};

describe('buildProvisionOperation — schema → the same op shape every form uses', () => {
  const op = buildProvisionOperation('sqs', 'aws_sqs_queue', RES);

  it('carries the provision op id, engineer routing and create semantics', () => {
    expect(op.id).toBe('provision-new:aws_sqs_queue');
    expect(op.exposure).toBe('engineer_only');
    expect(op.macd).toBe('Add');
    expect(op.group).toBe('create');
    expect(op.target.resourceType).toBe('aws_sqs_queue');
    expect(op.title).toBe('Provision a new SQS queue');
  });

  it('renders every fillable input as a param — required flags preserved', () => {
    const byName = new Map(op.params.map((p) => [p.name, p]));
    expect(byName.get('queue_name')).toMatchObject({ required: true, type: 'string' });
    expect(byName.get('delay_seconds')).toMatchObject({ required: false, type: 'number' });
    expect(byName.get('fifo_queue')).toMatchObject({ type: 'bool' });
    expect(byName.get('master_password')).toMatchObject({ sensitive: true });
  });

  it('lists, maps and JSON attributes become multi-line fields with plain help', () => {
    const byName = new Map(op.params.map((p) => [p.name, p]));
    expect(byName.get('subnet_ids')).toMatchObject({ uiWidget: 'textarea' });
    expect(byName.get('tags')?.help).toContain('key = value');
    expect(byName.get('policy_document')?.help).toContain('JSON');
  });

  it('single nested blocks flatten to grouped dotted params', () => {
    const kms = op.params.find((p) => p.name === 'encryption.kms_key_id');
    expect(kms).toMatchObject({ group: 'encryption' });
  });

  it('repeated blocks become ONE JSON entry field, required when min_items>0, with a real example', () => {
    const rule = op.params.find((p) => p.name === 'rule');
    expect(rule).toMatchObject({ required: true, uiWidget: 'textarea' });
    expect(rule?.help).toContain('"action"');
  });

  it('flows through validateParams unchanged: required fields enforce', () => {
    const bad = validateParams(op, {}, EMPTY_INVENTORY);
    expect(bad.ok).toBe(false);
    expect(bad.errors['queue_name']).toBeTruthy();
    expect(bad.errors['rule']).toBeTruthy();

    const good = validateParams(
      op,
      { queue_name: 'orders', rule: '[{"action":"allow"}]' },
      EMPTY_INVENTORY,
    );
    expect(good.ok).toBe(true);
  });

  it('flows through buildRequestDraft into a normal engineer-track request', () => {
    const draft = buildRequestDraft(
      op,
      '(new)',
      { queue_name: 'orders', rule: '[{"action":"allow"}]' },
      'Orders team needs a queue for the new intake flow.',
      getCurrentUser().id,
    );
    expect(draft.operationId).toBe('provision-new:aws_sqs_queue');
    expect(draft.exposure).toBe('engineer_only');
    expect(isSchemaProvisionRequest(draft)).toBe(true);

    const summary = describeProvisionRequest(draft);
    expect(summary?.resourceType).toBe('aws_sqs_queue');
    expect(summary?.rows.map((r) => r.label)).toContain('Queue name');
  });
});

describe('azure provision — the SAME seams over the committed azurerm catalog', () => {
  // The real committed azure chunk (generated by scripts/gen-provider-catalog.ts
  // -- ... azure), not a fixture: proves the both-cloud catalog stands up an
  // azurerm type through the identical provision pipeline the aws path uses.
  const chunk = acrChunk as unknown as CatalogServiceChunk;
  const res = chunk.types['azurerm_container_registry']!;
  const op = buildProvisionOperation('acr', 'azurerm_container_registry', res);

  it('synthesizes an engineer-routed create op for the azurerm type', () => {
    expect(op.id).toBe('provision-new:azurerm_container_registry');
    expect(op.exposure).toBe('engineer_only');
    expect(op.macd).toBe('Add');
    expect(op.target.resourceType).toBe('azurerm_container_registry');
    // Service name and type label coincide → the title never doubles up.
    expect(op.title).toBe('Provision a new Container Registry');
  });

  it('carries the schema’s real fillable params — required flags preserved, outputs dropped', () => {
    const byName = new Map(op.params.map((p) => [p.name, p]));
    expect(byName.get('name')).toMatchObject({ required: true });
    expect(byName.get('resource_group_name')).toMatchObject({ required: true });
    expect(byName.get('sku')).toMatchObject({ required: true });
    // Computed-only outputs are never fillable inputs.
    expect(byName.has('login_server')).toBe(false);
    expect(byName.has('admin_password')).toBe(false);
  });

  it('flows through validateParams: empty is rejected, required-filled passes', () => {
    const bad = validateParams(op, {}, EMPTY_INVENTORY);
    expect(bad.ok).toBe(false);
    expect(bad.errors['name']).toBeTruthy();

    const filled: Record<string, unknown> = {};
    for (const p of op.params.filter((x) => x.required)) {
      filled[p.name] = p.type === 'number' ? 1 : p.type === 'bool' ? true : 'x';
    }
    const good = validateParams(op, filled, EMPTY_INVENTORY);
    expect(good.ok).toBe(true);
  });
});

describe('the provision op id round-trip and titles', () => {
  it('round-trips the resource type', () => {
    expect(provisionResourceType(provisionOperationId('aws_ecs_service'))).toBe('aws_ecs_service');
    expect(provisionResourceType('ebs-grow')).toBeNull();
  });

  it('titles read plainly, service first, acronyms intact', () => {
    expect(provisionRequestTitle({ operationId: 'provision-new:aws_sqs_queue' })).toBe(
      'Provision a new SQS queue',
    );
    expect(provisionRequestTitle({ operationId: 'provision-new:aws_db_instance' })).toBe(
      'Provision a new RDS instance',
    );
    // A bare type whose label IS the service never doubles up.
    expect(provisionRequestTitle({ operationId: 'provision-new:aws_vpc' })).toBe(
      'Provision a new VPC',
    );
    // Azure provision requests title the same way, from the azurerm type alone.
    expect(
      provisionRequestTitle({ operationId: 'provision-new:azurerm_container_registry' }),
    ).toBe('Provision a new Container Registry');
    // Anything else falls back to the raw id — same contract as beyondCatalogTitle.
    expect(provisionRequestTitle({ operationId: 'ebs-grow' })).toBe('ebs-grow');
  });

  it('collapses PARTIAL azure service/label overlap, but leaves aws brands intact', () => {
    // AZURE: an azure service name is machine-derived from the same azurerm_*
    // family as the type label, so the two share their leading word with only a
    // generic service suffix differing. The label carries the product name in
    // full, so it stands alone — no "Kubernetes Service kubernetes Cluster".
    expect(
      provisionRequestTitle({ operationId: 'provision-new:azurerm_kubernetes_cluster' }),
    ).toBe('Provision a new Kubernetes Cluster');
    // Plural service ("Managed Disks"/"Virtual Machines") vs singular label.
    expect(provisionRequestTitle({ operationId: 'provision-new:azurerm_managed_disk' })).toBe(
      'Provision a new Managed Disk',
    );
    expect(provisionRequestTitle({ operationId: 'provision-new:azurerm_virtual_machine' })).toBe(
      'Provision a new Virtual Machine',
    );
    // AWS: service names are curated distinct brands where a shared leading word
    // is meaningful — collapsing would drop real identity, so partial overlap is
    // KEPT (only exact overlap dedups, byte-for-byte as before this change).
    expect(provisionRequestTitle({ operationId: 'provision-new:aws_imagebuilder_image' })).toBe(
      'Provision a new Image Builder image',
    );
    expect(provisionRequestTitle({ operationId: 'provision-new:aws_apigatewayv2_api' })).toBe(
      'Provision a new API Gateway api',
    );
  });
});

describe('blockExample — the JSON skeleton in repeated-block help', () => {
  it('builds the entry from the block’s own attributes', () => {
    expect(
      blockExample({ n: 'rule', m: 'list', attrs: [{ n: 'action', t: 'string', r: 1 }], blocks: [] }),
    ).toBe('[{"action":"…"}]');
  });
});

describe('hybrid linkage — the estate’s hand-authored create forms lead', () => {
  const byType = manifestCreateOpsByType(manifests);

  it('finds the bundled create baselines by the type they stand up', () => {
    // The estate catalog provisions EC2 instances and S3 buckets by hand.
    expect(byType.get('aws_instance')?.some((op) => op.id === 'ec2-provision-instance')).toBe(true);
    expect(byType.get('aws_s3_bucket')?.some((op) => op.id === 's3-create-bucket')).toBe(true);
  });

  it('createdTypeOf reads the synthesized block when one is named (aws or azurerm)', () => {
    expect(
      createdTypeOf({
        codemodOp: 'append_block',
        target: { resourceType: 'aws_ebs_volume', block: 'aws_ebs_snapshot.<name>' },
      } as never),
    ).toBe('aws_ebs_snapshot');
    expect(
      createdTypeOf({
        codemodOp: 'append_block',
        target: { resourceType: 'azurerm_virtual_network', block: 'azurerm_subnet.<name>' },
      } as never),
    ).toBe('azurerm_subnet');
  });
});

describe('groupProviderServices — category grouping preserves generated order', () => {
  const index: CatalogIndex = {
    provider: 'hashicorp/aws',
    providerVersion: '6.53.0',
    services: [
      { slug: 'ec2', name: 'EC2', category: 'Compute', types: [] },
      { slug: 'lambda', name: 'Lambda', category: 'Compute', types: [] },
      { slug: 's3', name: 'S3', category: 'Storage', types: [] },
    ],
  };
  it('one group per category run, services kept in order', () => {
    const groups = groupProviderServices(index);
    expect(groups.map((g) => g.category)).toEqual(['Compute', 'Storage']);
    expect(groups[0]?.services.map((s) => s.slug)).toEqual(['ec2', 'lambda']);
  });
});

describe('paramsFor — ordering', () => {
  it('top-level attributes come before nested-block fields', () => {
    const names = paramsFor(RES).map((p) => p.name);
    expect(names.indexOf('queue_name')).toBeLessThan(names.indexOf('encryption.kms_key_id'));
    expect(names.indexOf('encryption.kms_key_id')).toBeLessThan(names.indexOf('rule'));
  });
});
