/**
 * The active project scope for all project-scoped stores.
 * Set by ProjectProvider on route change; stores compute their storage key
 * AT CALL TIME so switching projects never needs a reload. Accounts and the
 * session are GLOBAL — never scope them.
 *
 * Data-birth (docs/superpowers/specs/2026-07-21-ccp-data-birth-generic-onboarding.md,
 * lane B item 1): NO unconditional bundled default. A fresh install has no
 * estate until one is onboarded, so the bare/unset scope is the empty string
 * — {@link hasActiveProject} is how a caller tells "nothing chosen yet" apart
 * from a real (possibly empty-looking) id. `lib/httpApi.ts`'s request() reads
 * this to decide whether the acting-account header rides at all: unscoped
 * (login, and any other pre-estate call) sends none, so the server's own
 * header-less default (the reserved control-plane scope) applies — never a
 * guessed estate id an unauthenticated or estate-less caller has no business
 * asserting. Mock/standalone's "loads the sample by default" behavior
 * (item 4) is set explicitly by lib/api.ts's module init, not baked in here.
 */
let current = '';

export function currentProjectId(): string {
  return current;
}
export function setProjectScope(id: string): void {
  current = id;
}
/** Test-only alias, for symmetry with the other stores' reset helpers. */
export const setProjectScopeForTests = setProjectScope;

/** True once something has actually been scoped (a route resolved a project,
 * or the sample/mock default ran) — false for the bare pre-estate state, e.g.
 * `/login` or a real install's first-run screen before any estate exists. */
export function hasActiveProject(): boolean {
  return current !== '';
}

/**
 * The bundled sample estate's id — a synthetic capture generated by the real
 * pipeline (build-inventory.py + extract-blocks.ts over
 * ccp/app/fixtures-estate/), kept as an explicitly-loaded, clearly-labeled
 * SAMPLE, never a privileged runtime default. The literal id lives here,
 * once, so `lib/httpApi.ts`, `lib/blockSource.ts`, and `lib/api.ts` name the
 * same constant instead of independent 'sample' string literals.
 */
export const SAMPLE_ESTATE_ID = 'sample';

/** Compute a project-scoped storage key: ccp.<project>.<store>.v1 */
export function scopedKey(store: string): string {
  return `ccp.${current}.${store}.v1`;
}
