import type { ChangeRequest, ManifestOperation, ManifestParam, ServiceManifest } from '@/types';
import { chipLabelFor, humanizeAttr } from '@/lib/chipLabel';
import { isProvisionAdd } from '@/lib/actionPicker';
import { providerOfType, type CloudProvider } from '@/lib/providerDisplay';
import {
  serviceDisplayMeta,
  serviceForType,
  typeLabel,
  type CatalogAttr,
  type CatalogBlock,
  type CatalogIndex,
  type CatalogResource,
  type CatalogServiceChunk,
  type CatalogServiceEntry,
  type CatalogTypeSummary,
} from '@/lib/providerCatalogGen';

/**
 * Runtime access to the generated provision catalog — every AWS service the
 * pinned Terraform provider supports, with the fillable parameters of every
 * resource type (generated by scripts/gen-provider-catalog.ts; see
 * src/lib/providerCatalogGen.ts for what is kept/dropped).
 *
 * Loading mirrors the block-source corpus (lib/blockSource.ts): the index and
 * each per-service chunk are their OWN lazy chunks via dynamic import — no
 * network, no bundle weight on initial load, standalone invariant untouched.
 *
 * A provision drafted from this catalog is a normal ChangeRequest whose
 * operationId carries {@link PROVISION_OP_PREFIX} — the same "no manifest op
 * behind the id" pattern the beyond-catalog request uses. It always routes to
 * an engineer (exposure engineer_only): the portal captures the FULL parameter
 * sheet, and the engineer authors the Terraform from it after approval.
 */

export type {
  CatalogAttr,
  CatalogBlock,
  CatalogIndex,
  CatalogResource,
  CatalogServiceChunk,
  CatalogServiceEntry,
  CatalogTypeSummary,
};

/* ── Lazy data access ──────────────────────────────────────────────────────── */

const indexCache: Partial<Record<CloudProvider, CatalogIndex>> = {};

/** The catalog index (every service + its resource types) for a provider — aws
 * (default) or azure. One lazy chunk per provider: an aws project never pulls
 * the azure index and vice versa. */
export async function loadProviderIndex(provider: CloudProvider = 'aws'): Promise<CatalogIndex> {
  const cached = indexCache[provider];
  if (cached) return cached;
  const mod =
    provider === 'azure'
      ? await import('@/data/provider-catalog-azure/index.json')
      : await import('@/data/provider-catalog/index.json');
  const idx = mod.default as unknown as CatalogIndex;
  indexCache[provider] = idx;
  return idx;
}

// Non-eager globs → each services/<slug>.json becomes its own lazy chunk,
// exactly like the block-source corpus. One glob per provider tree.
const AWS_CHUNKS = import.meta.glob<{ default: CatalogServiceChunk }>(
  '../data/provider-catalog/services/*.json',
);
const AZURE_CHUNKS = import.meta.glob<{ default: CatalogServiceChunk }>(
  '../data/provider-catalog-azure/services/*.json',
);

const chunkCache = new Map<string, CatalogServiceChunk>();

/** One service's full parameter data for a provider, or null for an unknown
 * slug. The cache key is provider-scoped so a slug shared across clouds (batch,
 * dms, resource-groups…) never returns the wrong cloud's chunk. */
export async function loadServiceChunk(
  provider: CloudProvider,
  slug: string,
): Promise<CatalogServiceChunk | null> {
  const key = `${provider}:${slug}`;
  const cached = chunkCache.get(key);
  if (cached) return cached;
  const glob = provider === 'azure' ? AZURE_CHUNKS : AWS_CHUNKS;
  const path =
    provider === 'azure'
      ? `../data/provider-catalog-azure/services/${slug}.json`
      : `../data/provider-catalog/services/${slug}.json`;
  const loader = glob[path];
  if (!loader) return null;
  const chunk = (await loader()).default;
  chunkCache.set(key, chunk);
  return chunk;
}

/* ── Category grouping (for the provision page) ────────────────────────────── */

export interface ProviderCategoryGroup {
  category: string;
  services: CatalogServiceEntry[];
}

/** Group the index's services by category, preserving the generated order
 * (the generator already sorts categories and names). */
export function groupProviderServices(index: CatalogIndex): ProviderCategoryGroup[] {
  const groups: ProviderCategoryGroup[] = [];
  let current: ProviderCategoryGroup | null = null;
  for (const service of index.services) {
    if (!current || current.category !== service.category) {
      current = { category: service.category, services: [] };
      groups.push(current);
    }
    current.services.push(service);
  }
  return groups;
}

/* ── The provision request kind (no manifest op behind the id, on purpose) ─── */

export const PROVISION_OP_PREFIX = 'provision-new:';

export function provisionOperationId(resourceType: string): string {
  return PROVISION_OP_PREFIX + resourceType;
}

/** The resource type behind a provision operation id, or null. */
export function provisionResourceType(operationId: string): string | null {
  return operationId.startsWith(PROVISION_OP_PREFIX)
    ? operationId.slice(PROVISION_OP_PREFIX.length)
    : null;
}

export function isSchemaProvisionRequest(request: Pick<ChangeRequest, 'operationId'>): boolean {
  return request.operationId.startsWith(PROVISION_OP_PREFIX);
}

/** The provision-page path that stands up `resourceType`: the service's page
 * (`/provision/:service`) with that type preselected via `?type=`. The slug is
 * the catalog's own grouping (serviceForType, provider-aware), so the type is
 * guaranteed to be in that service's chunk. Op-less service tiles and consoles
 * deep-link here instead of the retired `/provision?type=` form. */
export function provisionPathFor(resourceType: string): string {
  return `/provision/${serviceForType(resourceType)}?type=${resourceType}`;
}

/** "DB instance" → "DB instance", "Queue" → "queue" — lowercase only a
 * plainly-cased first word so acronyms survive mid-sentence. */
function lowerFirst(label: string): string {
  if (label.length > 1 && label[1] === label[1]?.toLowerCase()) {
    return label.charAt(0).toLowerCase() + label.slice(1);
  }
  return label;
}

/** Plain title for a provision request: "Provision a new SQS queue". */
export function provisionRequestTitle(
  request: Pick<ChangeRequest, 'operationId'>,
): string {
  const resourceType = provisionResourceType(request.operationId);
  if (!resourceType) return request.operationId;
  return provisionTitleFor(resourceType);
}

export function provisionTitleFor(resourceType: string): string {
  const provider = providerOfType(resourceType);
  const service = serviceDisplayMeta(serviceForType(resourceType), provider).name;
  const label = typeLabel(resourceType);
  return `Provision a new ${composeProvisionNoun(service, label, provider)}`;
}

/**
 * The "<service> <type>" noun phrase inside a provision title, with redundant
 * service/label overlap collapsed so a type whose label repeats its service
 * name never reads twice.
 *
 *  - EXACT overlap (either cloud): the label IS the service ("aws_vpc" → VPC,
 *    "azurerm_container_registry" → Container Registry) → the single name, no
 *    echo ("Provision a new VPC").
 *  - PARTIAL overlap (AZURE only): an azure service display name is machine-
 *    derived from the same azurerm_* family as the type label, so the two
 *    routinely share their leading word(s) with only a generic service suffix
 *    differing ("Kubernetes Service" + "Kubernetes Cluster", "Virtual Machines"
 *    + "Virtual Machine Extension"). When they share the leading word the label
 *    already carries the product name in full, so it stands alone ("Provision a
 *    new Kubernetes Cluster"). AWS service names are curated distinct brands
 *    where a shared leading word is meaningful ("Image Builder" + "Image
 *    recipe", "Certificate Manager" + "Certificate"); collapsing there would
 *    drop real identity, so aws keeps the exact-overlap-only dedup, byte-for-
 *    byte as before.
 *  - otherwise: the service prefixes the lower-cased label ("Provision a new
 *    SQS queue").
 */
function composeProvisionNoun(service: string, label: string, provider: CloudProvider): string {
  if (label.toLowerCase() === service.toLowerCase()) return service;
  if (provider === 'azure') {
    const serviceWords = service.split(/\s+/).filter((w) => w.length > 0);
    const labelWords = label.split(/\s+/).filter((w) => w.length > 0);
    if (
      serviceWords.length > 0 &&
      labelWords.length > 0 &&
      serviceWords[0]!.toLowerCase() === labelWords[0]!.toLowerCase()
    ) {
      return label;
    }
  }
  return `${service} ${lowerFirst(label)}`;
}

/** The standing note on every provision-request panel: what the approval
 * authorizes. Mirrors the beyond-catalog note's honesty. */
export const PROVISION_NOTE =
  'The Terraform for this new resource is authored by an engineer from the parameter sheet below — the approval here authorizes the work, not a diff.';

export interface ProvisionRow {
  label: string;
  value: string;
}

export interface ProvisionSummary {
  resourceType: string;
  service: string;
  rows: ProvisionRow[];
}

function rowValue(v: unknown): string {
  if (Array.isArray(v)) return v.map(String).join(', ');
  if (typeof v === 'object' && v !== null) return JSON.stringify(v);
  return String(v);
}

/** Human label for a stored param key ("timeouts" never appears; dotted keys
 * are nested-block paths: "point_in_time_recovery.enabled"). */
export function provisionRowLabel(key: string): string {
  return key
    .split('.')
    .map((part) => chipLabelFor(part))
    .join(' — ');
}

/** Shape a provision request's stored params into the reviewer's parameter
 * sheet. Returns null for any other request kind — callers branch on this. */
export function describeProvisionRequest(request: ChangeRequest): ProvisionSummary | null {
  const resourceType = provisionResourceType(request.operationId);
  if (!resourceType) return null;
  const rows: ProvisionRow[] = [];
  for (const [key, v] of Object.entries(request.params)) {
    if (v === undefined || v === null || v === '') continue;
    rows.push({ label: provisionRowLabel(key), value: rowValue(v) });
  }
  return { resourceType, service: request.service, rows };
}

/* ── Schema → form operation (the generated provisioning form) ─────────────── */

/** Example JSON skeleton for a repeated/deep block's entry field, generated
 * from the block's own attributes so the requester sees the real shape. */
export function blockExample(block: CatalogBlock): string {
  const entry: Record<string, unknown> = {};
  for (const a of block.attrs.slice(0, 4)) {
    entry[a.n] =
      a.t === 'number' ? 0 : a.t === 'bool' ? false : a.t === 'list' ? [] : a.t === 'map' ? {} : '…';
  }
  if (Object.keys(entry).length === 0) entry['…'] = '…';
  const one = JSON.stringify(entry);
  return block.m === 'single' ? one : `[${one}]`;
}

function attrParam(a: CatalogAttr, path: string[], group: string | undefined): ManifestParam {
  const name = [...path, a.n].join('.');
  const param: ManifestParam = {
    name,
    label: chipLabelFor(a.n),
    type: a.t === 'number' ? 'number' : a.t === 'bool' ? 'bool' : 'string',
    source: 'user_input',
    required: a.r === 1,
  };
  if (a.s === 1) param.sensitive = true;
  if (group) param.group = group;
  if (a.t === 'list') {
    param.uiWidget = 'textarea';
    param.help =
      a.et === 'number'
        ? 'A list — one number per line.'
        : a.et === 'bool'
          ? 'A list — one true/false per line.'
          : 'A list — one value per line.';
  } else if (a.t === 'map') {
    param.uiWidget = 'textarea';
    param.help = 'One entry per line, written as key = value.';
  } else if (a.t === 'json') {
    param.uiWidget = 'textarea';
    param.help = 'A structured value — enter it as JSON.';
  }
  return param;
}

function blockEntryParam(block: CatalogBlock, path: string[]): ManifestParam {
  const name = [...path, block.n].join('.');
  const label = chipLabelFor(block.n);
  const required = (block.min ?? 0) > 0;
  const repeats = block.m !== 'single';
  const help = block.json
    ? `${repeats ? 'One JSON entry per item — this section repeats.' : 'Enter this section as JSON.'} Its full structure is too deep for a flat form; an engineer completes it from what you provide.`
    : `${repeats ? 'This section repeats — enter a JSON list, one entry per item.' : 'Enter this section as JSON.'} Example: ${blockExample(block)}`;
  return {
    name,
    label,
    type: 'string',
    source: 'user_input',
    required,
    uiWidget: 'textarea',
    help,
    group: path.length > 0 ? path.join('--') : undefined,
  };
}

/** Flatten a compact resource into ordered manifest params: attributes first,
 * then nested blocks — single blocks become grouped fields, repeated or
 * depth-capped blocks become one JSON entry field each. */
export function paramsFor(res: CatalogResource): ManifestParam[] {
  const params: ManifestParam[] = [];
  const walk = (attrs: CatalogAttr[], blocks: CatalogBlock[], path: string[]): void => {
    const group = path.length > 0 ? path.join('--') : undefined;
    for (const a of attrs) params.push(attrParam(a, path, group));
    for (const b of blocks) {
      if (b.m === 'single' && !b.json) {
        walk(b.attrs, b.blocks, [...path, b.n]);
      } else {
        params.push(blockEntryParam(b, path));
      }
    }
  };
  walk(res.attrs, res.blocks, []);
  return params;
}

/**
 * Synthesize the ManifestOperation a generated provisioning form renders —
 * the SAME shape the hand-authored catalog uses, so SchemaForm,
 * validateParams and buildRequestDraft all work unchanged. It exists only in
 * memory: getOperation() never returns it, and the request surfaces render
 * provision requests from their stored params (describeProvisionRequest).
 */
export function buildProvisionOperation(
  serviceSlug: string,
  resourceType: string,
  res: CatalogResource,
): ManifestOperation {
  return {
    id: provisionOperationId(resourceType),
    service: serviceSlug,
    macd: 'Add',
    codemodOp: 'create_resource',
    title: provisionTitleFor(resourceType),
    summary: 'Fill in the parameters for the new resource — an engineer authors the Terraform from them.',
    description: `Requests a new ${resourceType} resource with the parameters below.`,
    target: { resourceType },
    params: paramsFor(res),
    riskFloor: 'HIGH',
    reversible: true,
    downtime: 'none',
    exposure: 'engineer_only',
    forcesReplace: false,
    terraformCapability: `resource "${resourceType}" — full parameter sheet from the provider schema`,
    group: 'create',
  };
}

/* ── Hybrid linkage: prefer the estate's hand-authored create forms ─────────── */

/** The resource type a provision-class create op stands up. */
export function createdTypeOf(op: ManifestOperation): string {
  const block = op.target.block;
  if (
    op.codemodOp === 'append_block' &&
    block &&
    (block.startsWith('aws_') || block.startsWith('azurerm_'))
  ) {
    return block.split('.')[0] ?? block;
  }
  return op.target.resourceType;
}

/**
 * Every hand-authored provision baseline in the ACTIVE project's manifests,
 * keyed by the resource type it creates. The provision pages PREFER these
 * (richer: allow-lists, live pickers, estate bounds) over the generated form.
 */
export function manifestCreateOpsByType(
  manifests: ServiceManifest[],
): Map<string, ManifestOperation[]> {
  const byType = new Map<string, ManifestOperation[]>();
  for (const manifest of manifests) {
    for (const op of manifest.operations) {
      if (op.group !== 'create' || !isProvisionAdd(op)) continue;
      const type = createdTypeOf(op);
      const list = byType.get(type);
      if (list) list.push(op);
      else byType.set(type, [op]);
    }
  }
  return byType;
}

/** Search haystack for one service entry (name, slug, type names + labels). */
export function serviceMatches(entry: CatalogServiceEntry, q: string): boolean {
  if (entry.name.toLowerCase().includes(q) || entry.slug.includes(q)) return true;
  return entry.types.some((t) => t.t.includes(q) || t.label.toLowerCase().includes(q));
}

/** Re-humanize a label for use mid-sentence (exported for the pages). */
export { lowerFirst as lowerFirstWord, humanizeAttr };
