#!/usr/bin/env python3
"""gen-imports.py — discovery manifest -> imports.tf (Terraform import blocks).

The Azure sibling of importer/kit/gen-imports.py, and — deliberately — the SOLE emitter of
imports.tf. aztfexport can also emit import blocks (--generate-import-block), but the kit
never uses that: keeping generation here means the plannable PR artifact is deterministic,
stdlib-only, version-stable, and secret-free BY CONSTRUCTION (a block carries only
type/label/id — never an attribute value, so no secret can enter git through it).

  - one `import { to = <type>.<label>  id = "<arm-id>" }` block per import-disposition row
    (two-space indent, id always quoted)
  - blocks sorted by (type, label)
  - a banner header carrying subscription/tenant/location/provenance
  - the import id is the Azure resource id verbatim (e.g.
    /subscriptions/<sub>/resourceGroups/<rg>/providers/Microsoft.Network/virtualNetworks/<n>).
    Unlike the AWS kit there is NO --id-region-suffix: an ARM id already scopes subscription
    and resource group, so there is no ambiguity to disambiguate.

The output is NOT runnable from importer/kit-azure/ — like the AWS archive, import blocks must sit
in the SAME root as the resource definitions they target. The runbook step this feeds
(docs/runbooks/azure-subscription-import.md): copy imports.tf into environments/<env>-azure/ and
generate the bodies with aztfexport --hcl-only (or `terraform plan -generate-config-out` as
the fallback).

Refusals (never a silent skip):
  - a resource row missing type/id/label          -> REFUSE MALFORMED_ROW
  - a label that is not a valid HCL identifier    -> REFUSE BAD_LABEL
  - two rows landing on the same address          -> REFUSE DUPLICATE_ADDRESS
Rows whose disposition is not "import" are excluded and COUNTED on stdout.

Stdlib only. Deterministic: same manifest in, byte-identical imports.tf out.
Exit codes: 0 ok · 2 refusal.
"""
import argparse
import hashlib
import json
import re
import sys

LABEL_RE = re.compile(r"^[a-z_][a-z0-9_]*$")


def refuse(code, msg):
    print(f"REFUSE {code}: {msg}", file=sys.stderr)
    sys.exit(2)


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--manifest", required=True, help="discovery-manifest.json from discover.py build")
    p.add_argument("--out", required=True, help="imports.tf to write")
    p.add_argument("--phase", type=int, default=0,
                   help="emit only this strategy.md phase (2/3/4/5); default all — use per-phase "
                        "batches to honor strategy.md's small-batches rule")
    args = p.parse_args(argv)

    try:
        with open(args.manifest) as fh:
            manifest = json.load(fh)
    except (OSError, json.JSONDecodeError) as e:
        refuse("BAD_MANIFEST", f"cannot read {args.manifest}: {e}")

    rows = manifest.get("resources", [])
    if not isinstance(rows, list):
        refuse("BAD_MANIFEST", "manifest.resources is not a list")

    excluded = {}
    selected = []
    for i, row in enumerate(rows):
        for key in ("type", "id", "label"):
            if not isinstance(row.get(key), str) or not row[key]:
                refuse("MALFORMED_ROW", f"resources[{i}] is missing '{key}' — refusing rather than dropping it")
        disp = row.get("disposition", "import")
        if disp != "import":
            excluded[disp] = excluded.get(disp, 0) + 1
            continue
        if args.phase and row.get("phase") != args.phase:
            continue
        if not LABEL_RE.match(row["label"]):
            refuse("BAD_LABEL", f"{row['type']} label {row['label']!r} is not a valid HCL identifier — "
                                "curate it in the manifest and re-run")
        selected.append(row)

    selected.sort(key=lambda r: (r["type"], r["label"]))
    seen = set()
    for row in selected:
        addr = f"{row['type']}.{row['label']}"
        if addr in seen:
            refuse("DUPLICATE_ADDRESS", f"two resources map to {addr} — fix labels in the manifest")
        seen.add(addr)

    manifest_sha = hashlib.sha256(open(args.manifest, "rb").read()).hexdigest()
    subscription = manifest.get("subscription", "unknown")
    tenant = manifest.get("tenant", "unknown")
    location = manifest.get("location", "unknown")
    captured = manifest.get("capturedAt", "unknown")
    phase_note = f" (phase {args.phase} only)" if args.phase else ""

    lines = [
        "# " + "─" * 77,
        f"# IMPORT MAP — generated by importer/kit-azure/gen-imports.py, NOT YET APPLIED{phase_note}.",
        "#",
        f"# Subscription {subscription}, tenant {tenant}, location {location}. Captured {captured}.",
        f"# Source manifest sha256: {manifest_sha}",
        f"# {len(selected)} import block(s). Read-only capture; applying these blocks only",
        "# writes STATE (import never mutates live resources).",
        "#",
        "# Not runnable from importer/kit-azure/ — import blocks must sit in the same root as the",
        "# resource definitions they target (see importer/kit-azure/README.md). Next step:",
        "#   copy into environments/<env>-azure/ then generate bodies with",
        "#   aztfexport --hcl-only  (or: terraform plan -generate-config-out=generated.tf)",
        "# " + "─" * 77,
        "",
    ]
    for row in selected:
        lines.append("import {")
        lines.append(f"  to = {row['type']}.{row['label']}")
        lines.append(f'  id = "{row["id"]}"')
        lines.append("}")
        lines.append("")

    with open(args.out, "w") as fh:
        fh.write("\n".join(lines))

    print(f"WROTE {len(selected)} import block(s) to {args.out}{phase_note}")
    for disp in sorted(excluded):
        print(f"  excluded {excluded[disp]} row(s) with disposition '{disp}' (deliberate, per manifest)")
    print("next: copy into environments/<env>-azure/ then generate bodies with\n"
          "  aztfexport --hcl-only   (or the fallback: terraform plan -generate-config-out=generated.tf)\n"
          "(docs/runbooks/azure-subscription-import.md)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
