import type { ServiceManifest } from '@/types';
import { parseManifests } from '@/types/manifestSchema';

/**
 * The bundled module manifests — the runtime catalog. Each `*.json` in this
 * directory is picked up automatically (drop a file in → it registers, with no
 * edit here), then validated against the manifest schema so a malformed manifest
 * fails loudly instead of via a blind `as unknown as` cast. In production these
 * are generated by `catalogctl manifest` from each service module's schema; the
 * union of all operations IS what the frontend can do, with no model at runtime.
 */
const modules = import.meta.glob<{ default: unknown }>('./*.json', { eager: true });

const raw = Object.keys(modules)
  .sort()
  .map((key) => modules[key]!.default);

export const manifests: ServiceManifest[] = parseManifests(raw);
