package prprep

import (
	"fmt"
	"strings"

	"github.com/masjamsss/cloud-control-plane/tools/catalogctl/internal/request"
)

// renderPRBody produces the deterministic Markdown PR body. It embeds the
// signed approval record (who/when/policyVersion/digest), the schedule (window +
// earliest-apply), the list of changed files, and the REDACTED catalogctl edit diff
// (edit redacts secrets before diffing, so the body never leaks a token). Everything
// is sourced from the request + the edit diff — no clock reads — so the same request
// always yields byte-identical output (golden-testable).
func renderPRBody(r *request.Request, resolvedTarget string, files []string, diff string) string {
	target := r.Target
	if target == "" {
		target = resolvedTarget
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# ccp change request `%s`\n\n", r.ID)
	fmt.Fprintf(&b, "- **Operation:** `%s`\n", r.Item)
	fmt.Fprintf(&b, "- **Target:** `%s`\n", target)
	fmt.Fprintf(&b, "- **Requester:** `%s`\n", r.RequesterLogin)
	if r.CreatedAt != "" {
		fmt.Fprintf(&b, "- **Requested:** `%s`\n", r.CreatedAt)
	}
	b.WriteString("\n## Justification\n\n")
	b.WriteString(strings.TrimRight(r.Justification, "\n"))
	b.WriteString("\n")

	fmt.Fprintf(&b, "\n## Approvals (quorum: %d)\n\n", len(r.Approvals))
	b.WriteString("| Approver | Decided at | Policy version | Plan digest | Decision |\n")
	b.WriteString("|---|---|---|---|---|\n")
	for _, a := range r.Approvals {
		fmt.Fprintf(&b, "| %s | %s | %s | `%s` | %s |\n",
			dash(a.Approver), dash(a.ApprovedAt), dash(a.PolicyVersion), dashRaw(a.Digest), dash(a.Decision))
	}
	if d, ok := r.ApprovedDigest(); ok && d != "" {
		fmt.Fprintf(&b, "\n**Bound plan digest:** `%s` — CI re-verifies `sha256(plan.json)` equals this before merge (approve-this-exact-plan; W2).\n", d)
	} else {
		b.WriteString("\n**Bound plan digest:** _pending_ — CI computes `sha256(plan.json)` and approvals must be re-affirmed against it (W2).\n")
	}

	b.WriteString("\n## Schedule\n\n")
	if r.Window != nil {
		fmt.Fprintf(&b, "- **Window:** %s → %s (%s)\n", r.Window.Start, r.Window.End, r.Window.TZ)
	} else {
		b.WriteString("- **Window:** next scheduler tick after approval (no maintenance window)\n")
	}
	if r.EarliestApplyAt != "" {
		fmt.Fprintf(&b, "- **Earliest apply:** %s (ADR-0009 cooling-off)\n", r.EarliestApplyAt)
	} else {
		b.WriteString("- **Earliest apply:** none\n")
	}

	b.WriteString("\n## Change\n\nFiles edited by `catalogctl edit`:\n\n")
	for _, f := range files {
		if strings.HasPrefix(f, "requests/") || f == "PR_BODY.md" {
			continue // artifacts, not estate edits
		}
		fmt.Fprintf(&b, "- `%s`\n", f)
	}
	b.WriteString("\n<details><summary>catalogctl edit diff (redacted)</summary>\n\n```diff\n")
	b.WriteString(strings.TrimRight(diff, "\n"))
	b.WriteString("\n```\n\n</details>\n")

	fmt.Fprintf(&b, "\n## Plan digest & gate\n\n`requests/%s.plan-digest` is a PENDING placeholder. The CI plan job (W2) overwrites it with `sha256(plan.json)`, posts the `ccp/plan-digest` commit status, and runs `catalogctl plan-check` (R1–R6) against this request — a VIOLATION blocks the merge.\n", r.ID)

	fmt.Fprintf(&b, "\n---\n_Generated by `catalogctl pr-prepare`. PR seam: `gh pr create --head %s --title %q --body-file PR_BODY.md --label ccp:approved`._\n",
		branchName(r), prTitle(r))
	return b.String()
}

// dash renders "—" for an empty cell (keeps the table well-formed); dashRaw does the
// same but is used inside a code span where an empty value would render as “.
func dash(s string) string {
	if s == "" {
		return "—"
	}
	return s
}

func dashRaw(s string) string {
	if s == "" {
		return "—"
	}
	return s
}
