/**
 * ONE-SHOT backfill for the 0008 §3 action-picker taxonomy. Assigns every op
 * in every bundled manifest a `group` (one of the 8 fixed buckets) from its
 * id/title/macd/forcesReplace, and `pinned` (1-5) on up to 5 common SAFE
 * Change ops per resourceType. Human-reviewable first pass, per the decision
 * doc ("one-shot script from id/title patterns + human review") — not
 * expected to be perfect; the lint test (opTaxonomy.test.ts) enforces the
 * rules that must hold exactly.
 *
 * SAFETY: this script never touches any field but `group`/`pinned`. It edits
 * each manifest file as TEXT (not JSON.parse→JSON.stringify→write), inserting
 * two new lines right after each op's `"terraformCapability"` line (always
 * the op's last field per manifestSchema.ts). A round-trip through
 * JSON.stringify would silently re-encode some files' escaped `\uXXXX`
 * unicode sequences as literal UTF-8 characters (the 31 manifest files were
 * generated by more than one tool and are NOT byte-consistent on that axis),
 * corrupting hundreds of unrelated lines. The surgical text edit guarantees
 * every other byte in every file is untouched.
 *
 * Run: npx vite-node scripts/backfill-groups.ts
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const APP = join(dirname(fileURLToPath(import.meta.url)), '..');
const MANIFESTS = join(APP, 'src/data/manifests');
// The bootstrap sandbox project vendors its own small manifest catalog
// (src/data/projects/bootstrap/manifests/) validated by the SAME required
// ServiceManifestSchema — it needs group/pinned too, or flipping the schema
// to required (task 3) breaks bootstrapProject.test.ts / projectRegistry.test.ts.
// Its ~43 ops are id-for-id a subset of the main 680 (same macd/title/
// riskFloor/exposure/forcesReplace, confirmed by diffing the two catalogs),
// so classify() yields identical groups; pinned is still computed in this
// catalog's OWN scope (≤5 per resourceType among only ITS ops), which is the
// correct behavior — a picker showing the bootstrap project only ever offers
// the bootstrap project's ops for that resourceType.
const BOOTSTRAP_MANIFESTS = join(APP, 'src/data/projects/bootstrap/manifests');

// Mirror of the zod enum in src/types/manifestSchema.ts (opGroup). Scripts
// stay decoupled from src/ (tsconfig only type-checks "src"; see the other
// scripts in this dir), so the 8 values are duplicated here deliberately —
// keep in sync by hand.
type Group =
  | 'scale-performance'
  | 'availability-lifecycle'
  | 'connectivity-access'
  | 'protection-backup'
  | 'monitoring-alarms'
  | 'tags-naming'
  | 'danger-zone'
  | 'create';

interface OpForClassify {
  id: string;
  macd: 'Add' | 'Move' | 'Change' | 'Delete';
  title: string;
  target: { resourceType: string };
  riskFloor: 'LOW' | 'MEDIUM' | 'HIGH';
  exposure: 'l1_self_service' | 'l1_with_guardrails' | 'engineer_only';
  forcesReplace: boolean;
  // Present when re-running against an already-backfilled catalog (idempotency).
  group?: Group;
}

// ---------------------------------------------------------------------------
// Classification — first match wins. Order: explicit id overrides (hand-
// identified false positives from the keyword passes below) → macd:"Add" is
// always Create → Delete/Move/forcesReplace is always Danger zone (0008 §3:
// "63 Delete + 2 Move + destructive forcesReplace" — forcesReplace means AWS
// destroys+recreates the resource, which is destructive regardless of macd)
// → cross-cutting keyword themes, most-specific first → per-resourceType
// default for whatever theme dominates that AWS service's remaining surface.
// ---------------------------------------------------------------------------

const EXPLICIT: Record<string, Group> = {
  // IMDS access-control setting (does the metadata service expose instance
  // tags to code running ON the instance) — not an op that tags the resource.
  'ec2-set-imds-instance-metadata-tags': 'connectivity-access',
  // "recovery period" here is an alarm evaluation parameter (how long before
  // ALARM auto-returns to OK), not disaster/backup recovery.
  'cloudwatch-alarm-promql-recovery-period': 'monitoring-alarms',
  // EC2 auto-recovery reboots/migrates on hardware failure — an availability
  // (auto-healing) feature, not data protection.
  'ec2-set-auto-recovery': 'availability-lifecycle',
  // ML-model "deployment" toggle, not a software/infra deployment-lifecycle
  // op; keep consistent with its user-profile sibling
  // (sagemaker-set-canvas-direct-deploy-status, which has no "deployment"
  // word in its title and lands in connectivity-access via the resourceType
  // default below).
  'sagemaker-set-domain-canvas-direct-deploy-status': 'connectivity-access',
};

const TAGS_NAMING_RE = /\btags?\b|\brenam\w*\b|\bretag\b|\bdescription\b|\bcomment\b/i;

const PROTECTION_RE =
  /\bbackup\b|\bsnapshot\b|\breplicat\w*|\bencrypt\w*|\bversioning\b|\brecovery\b|\brotat\w*|\bmalware\b|\bpitr\b|point.?in.?time|deletion.?protection|\bvault\b|archive.?tier|\bretention\b|\bdlm\b|\bpublic.?access.?block\b|\bwaf\b/i;

const MONITORING_RE = /\balarm\b|\bdashboard\b|\bmetric\b|log.?group|\bmonitoring\b|\binsight\w*|\blog.?level\b/i;

const AVAILABILITY_RE =
  /health.?check|multi.?az|maintenance.?window|capacity.?rebalance|capacity.?reservation|termination.?polic\w*|instance.?refresh|\bsuspend\b|\bresume\b|blue.?green|instance.?lifetime|warm.?pool|\bstandby\b|\bfailover\b|(major|minor).?version.?upgrade|engine.?lifecycle|force.?delete|termination.?protect\w*|stop.?protect\w*|auto.?recovery|shutdown.?behavior|delete.?on.?termination|replica.?mode|\bdeployment\b|scale.?in.?protect\w*|az.?distribution|idle.?shutdown|idle.?timeout|\blifecycle\b/i;

const SCALE_RE =
  /\bresize\b|\bgrow\b|throughput|\biops\b|\bmemory\b|concurrency|instance.?class|instance.?type|cpu.?credit|cpu.?amd|nested.?virtualization|hibernation|enclave|market.?type|\bspot\b|\btenancy\b|dedicated.?log.?volume|warm.?throughput|gp2|gp3|volume.?type|\bttl\b|compression|http.?version|price.?class|\bstorage\b|scaling.?adjustment|\bcooldown\b|\bwarmup\b|adjustment.?magnitude|metric.?aggregation|adjust.*capacity|desired.?capacity|capacity.?type|parameter.?group|\bsnap.?start\b|billing.?mode|table.?class|architecture\b/i;

const CONNECTIVITY_RE =
  /\bauth\b|auth.?mode|access.?status|docker.?access|trusted.?identity|\boauth\b|\bsso\b|get.?password.?data|associate.?public.?ip|source.?dest.?check|\bhostname\b|\bimds\b|dns.?a.?record|dns.?aaaa|ebs.?optimized|primary.?ipv6|\bcors\b|mutual.?authentication|trust.?store|client.?certificate|\bmtls\b|network.?type|\bstreams\b|\bacl\b/i;

/** Per-resourceType fallback once no keyword theme matches. Chosen from each
 * AWS service's dominant remaining theme after the keyword passes above have
 * already carved out its tag/rename/protection/monitoring/availability/scale
 * ops (see the backfill run's printed histogram + report for the reasoning
 * behind ambiguous calls: SNS→monitoring, WAF/CloudTrail/Config→protection,
 * SageMaker/IAM→connectivity, DLM→protection). */
const RESOURCE_TYPE_DEFAULT: Record<string, Group> = {
  // Connectivity & access — network topology, DNS, TLS, identity/permission access.
  aws_acm_certificate: 'connectivity-access',
  aws_lb: 'connectivity-access',
  aws_lb_listener: 'connectivity-access',
  aws_lb_listener_rule: 'connectivity-access',
  aws_lb_listener_certificate: 'connectivity-access',
  aws_lb_target_group: 'connectivity-access',
  aws_security_group: 'connectivity-access',
  aws_network_acl: 'connectivity-access',
  aws_default_network_acl: 'connectivity-access',
  aws_route_table: 'connectivity-access',
  aws_route: 'connectivity-access',
  aws_route_table_association: 'connectivity-access',
  aws_eip: 'connectivity-access',
  aws_vpn_connection: 'connectivity-access',
  aws_customer_gateway: 'connectivity-access',
  aws_route53_record: 'connectivity-access',
  aws_route53_zone: 'connectivity-access',
  aws_vpc: 'connectivity-access',
  aws_vpc_endpoint: 'connectivity-access',
  aws_subnet: 'connectivity-access',
  aws_iam_role: 'connectivity-access',
  aws_iam_user: 'connectivity-access',
  aws_iam_group: 'connectivity-access',
  aws_iam_role_policy: 'connectivity-access',
  aws_iam_access_key: 'connectivity-access',
  aws_efs_mount_target: 'connectivity-access',
  aws_db_subnet_group: 'connectivity-access',
  aws_key_pair: 'connectivity-access',
  aws_s3_bucket: 'connectivity-access',
  aws_sagemaker_domain: 'connectivity-access',
  aws_sagemaker_user_profile: 'connectivity-access',
  aws_cloudfront_distribution: 'connectivity-access',

  // Scale & performance — sizing, throughput, capacity.
  aws_autoscaling_group: 'scale-performance',
  aws_autoscaling_policy: 'scale-performance',
  aws_db_instance: 'scale-performance',
  aws_dynamodb_table: 'scale-performance',
  aws_ebs_volume: 'scale-performance',
  aws_efs_file_system: 'scale-performance',
  aws_instance: 'scale-performance',
  aws_lambda_function: 'scale-performance',
  aws_lambda_provisioned_concurrency_config: 'scale-performance',
  aws_licensemanager_license_configuration: 'scale-performance',
  aws_licensemanager_association: 'scale-performance',
  aws_s3_bucket_lifecycle_configuration: 'scale-performance',

  // Protection & backup — data protection, compliance/audit, threat protection.
  aws_dlm_lifecycle_policy: 'protection-backup',
  aws_backup_plan: 'protection-backup',
  aws_backup_selection: 'protection-backup',
  aws_backup_vault: 'protection-backup',
  aws_db_snapshot: 'protection-backup',
  aws_cloudtrail: 'protection-backup',
  aws_config_config_rule: 'protection-backup',
  aws_config_configuration_recorder: 'protection-backup',
  aws_config_delivery_channel: 'protection-backup',
  aws_secretsmanager_secret: 'protection-backup',
  aws_secretsmanager_secret_rotation: 'protection-backup',
  aws_wafv2_web_acl: 'protection-backup',
  aws_wafv2_ip_set: 'protection-backup',
  aws_kms_key: 'protection-backup',
  aws_kms_alias: 'protection-backup',
  aws_efs_backup_policy: 'protection-backup',
  aws_ssm_parameter: 'protection-backup',
  aws_s3_bucket_public_access_block: 'protection-backup',
  aws_s3_bucket_versioning: 'protection-backup',

  // Monitoring & alarms — CloudWatch observability + the notification/event
  // plumbing that reports on it (EventBridge is legacy-named "CloudWatch
  // Events"; SNS here is overwhelmingly alarm/event delivery config).
  aws_cloudwatch_metric_alarm: 'monitoring-alarms',
  aws_cloudwatch_dashboard: 'monitoring-alarms',
  aws_cloudwatch_log_group: 'monitoring-alarms',
  aws_cloudwatch_event_rule: 'monitoring-alarms',
  aws_cloudwatch_event_target: 'monitoring-alarms',
  aws_sns_topic: 'monitoring-alarms',
  aws_sns_topic_subscription: 'monitoring-alarms',
};

function classify(op: OpForClassify): Group {
  // Idempotency: a re-run against an already-backfilled catalog (e.g. this
  // script's own second pass, or a future re-run) must never reclassify an
  // op that's already labeled — keep whatever a human may have hand-adjusted.
  if (op.group) return op.group;
  const explicit = EXPLICIT[op.id];
  if (explicit) return explicit;
  if (op.macd === 'Add') return 'create';
  if (op.macd === 'Delete' || op.macd === 'Move' || op.forcesReplace) return 'danger-zone';

  const hay = `${op.id} ${op.title}`;
  if (TAGS_NAMING_RE.test(hay)) return 'tags-naming';
  if (PROTECTION_RE.test(hay)) return 'protection-backup';
  if (MONITORING_RE.test(hay)) return 'monitoring-alarms';
  if (AVAILABILITY_RE.test(hay)) return 'availability-lifecycle';
  if (SCALE_RE.test(hay)) return 'scale-performance';
  if (CONNECTIVITY_RE.test(hay)) return 'connectivity-access';

  const byResourceType = RESOURCE_TYPE_DEFAULT[op.target.resourceType];
  if (byResourceType) return byResourceType;
  throw new Error(
    `backfill-groups: no rule matched op "${op.id}" (resourceType ${op.target.resourceType}) — ` +
      `add a keyword rule or a RESOURCE_TYPE_DEFAULT entry before re-running.`,
  );
}

// ---------------------------------------------------------------------------
// Pinned — up to 5 common SAFE Change ops per resourceType. "Safe" = not in
// the forbidden-for-pinning set (Delete/Move/engineer_only/forcesReplace —
// Add is also excluded here since Add ops never appear in the per-resource
// picker this field feeds; they get their own "Add new" grid). Ranked
// lowest-risk-first so genuinely low-stakes ops fill the shortlist before
// anything HIGH/guardrailed is ever pinned; ties break on catalog order for
// determinism.
// ---------------------------------------------------------------------------

const RISK_RANK: Record<OpForClassify['riskFloor'], number> = { LOW: 0, MEDIUM: 1, HIGH: 2 };
const EXPOSURE_RANK: Record<OpForClassify['exposure'], number> = {
  l1_self_service: 0,
  l1_with_guardrails: 1,
  engineer_only: 2,
};
const MAX_PINNED_PER_RESOURCE_TYPE = 5;

function computePinned(allOps: OpForClassify[]): Map<string, number> {
  const byResourceType = new Map<string, OpForClassify[]>();
  for (const op of allOps) {
    const list = byResourceType.get(op.target.resourceType) ?? [];
    list.push(op);
    byResourceType.set(op.target.resourceType, list);
  }

  const pinned = new Map<string, number>();
  for (const ops of byResourceType.values()) {
    const eligible = ops.filter(
      (o) => o.macd === 'Change' && o.exposure !== 'engineer_only' && !o.forcesReplace,
    );
    const ranked = [...eligible].sort(
      (a, b) => RISK_RANK[a.riskFloor] - RISK_RANK[b.riskFloor] || EXPOSURE_RANK[a.exposure] - EXPOSURE_RANK[b.exposure],
    );
    ranked.slice(0, MAX_PINNED_PER_RESOURCE_TYPE).forEach((op, i) => pinned.set(op.id, i + 1));
  }
  return pinned;
}

// ---------------------------------------------------------------------------
// Main — surgical per-file text edit (see file header for why not JSON.stringify).
// ---------------------------------------------------------------------------

// Trailing comma is optional so a re-run recognizes lines this script (or a
// prior run of it) has already touched, vs. the pristine "last field" form.
const TF_CAP_LINE_RE = /^(\s*)"terraformCapability":\s*(".*")(,)?$/;

interface CatalogResult {
  files: string[];
  allOps: OpForClassify[];
  groupOf: Map<string, Group>;
  pinnedOf: Map<string, number>;
}

/** Classify + pin + surgically rewrite every manifest JSON file in `dir`, as
 * its own independent catalog scope (pinned ranks are computed among only
 * this directory's ops — see BOOTSTRAP_MANIFESTS comment above for why). */
function backfillCatalog(dir: string): CatalogResult {
  const files = readdirSync(dir)
    .filter((f) => f.endsWith('.json'))
    .sort();

  // Pass 1: parse every file to build the whole-catalog op list (classify()
  // is per-op, but computePinned() needs every op in this catalog scope).
  const parsedByFile = new Map<string, { operations: OpForClassify[] }>();
  const allOps: OpForClassify[] = [];
  for (const f of files) {
    const raw = readFileSync(join(dir, f), 'utf8');
    const manifest = JSON.parse(raw) as { operations: OpForClassify[] };
    parsedByFile.set(f, manifest);
    allOps.push(...manifest.operations);
  }

  const groupOf = new Map<string, Group>();
  for (const op of allOps) groupOf.set(op.id, classify(op));
  const pinnedOf = computePinned(allOps);

  // Pass 2: surgical text edit per file.
  for (const f of files) {
    const path = join(dir, f);
    const text = readFileSync(path, 'utf8');
    const lines = text.split('\n');
    const ops = parsedByFile.get(f)!.operations;

    let opIndex = 0;
    const out: string[] = [];
    for (const line of lines) {
      const m = TF_CAP_LINE_RE.exec(line);
      if (!m) {
        out.push(line);
        continue;
      }
      const op = ops[opIndex];
      opIndex++;
      if (!op) throw new Error(`${f}: more "terraformCapability" lines than parsed operations`);
      if (op.group) {
        // Idempotency: already backfilled in a prior run (this op's group is
        // already followed by its group/pinned lines) — leave untouched.
        out.push(line);
        continue;
      }
      const indent = m[1]!;
      const group = groupOf.get(op.id);
      if (!group) throw new Error(`${f}: op ${op.id} has no computed group`);
      const pinned = pinnedOf.get(op.id);

      out.push(`${indent}"terraformCapability": ${m[2]!},`);
      if (pinned === undefined) {
        out.push(`${indent}"group": "${group}"`);
      } else {
        out.push(`${indent}"group": "${group}",`);
        out.push(`${indent}"pinned": ${pinned}`);
      }
    }
    if (opIndex !== ops.length) {
      throw new Error(`${f}: found ${opIndex} "terraformCapability" lines but parsed ${ops.length} operations`);
    }
    writeFileSync(path, out.join('\n'));
  }

  return { files, allOps, groupOf, pinnedOf };
}

function reportPinned(label: string, result: CatalogResult): void {
  const resourceTypesWithPinned = new Set(
    [...result.pinnedOf.keys()].map((id) => result.allOps.find((o) => o.id === id)!.target.resourceType),
  );
  console.log(
    `${label}: ${result.pinnedOf.size} ops pinned across ${resourceTypesWithPinned.size} resourceTypes (max ${MAX_PINNED_PER_RESOURCE_TYPE} each)`,
  );
}

function main(): void {
  const mainCatalog = backfillCatalog(MANIFESTS);
  if (mainCatalog.allOps.length !== 680) {
    console.warn(
      `WARNING: expected 680 ops in the main catalog, found ${mainCatalog.allOps.length} — histogram/measured comparison will be off.`,
    );
  }

  const bootstrap = backfillCatalog(BOOTSTRAP_MANIFESTS);

  // --- report (main catalog — the 0008 §3 measured comparison is scoped to it) ---
  const MEASURED: Record<Group, number> = {
    'scale-performance': 97,
    'availability-lifecycle': 40,
    'connectivity-access': 138,
    'protection-backup': 104,
    'monitoring-alarms': 68,
    'tags-naming': 111,
    'danger-zone': 65,
    create: 82,
  };
  const order: Group[] = [
    'create',
    'danger-zone',
    'scale-performance',
    'availability-lifecycle',
    'connectivity-access',
    'protection-backup',
    'monitoring-alarms',
    'tags-naming',
  ];
  const histogram = new Map<Group, number>();
  for (const g of mainCatalog.groupOf.values()) histogram.set(g, (histogram.get(g) ?? 0) + 1);

  console.log('\n=== group histogram vs measured (0008 §3) — main catalog ===');
  let total = 0;
  for (const g of order) {
    const actual = histogram.get(g) ?? 0;
    total += actual;
    const delta = actual - MEASURED[g];
    const sign = delta >= 0 ? '+' : '';
    console.log(`${g.padEnd(24)} actual=${String(actual).padStart(4)}  measured~${String(MEASURED[g]).padStart(4)}  delta=${sign}${delta}`);
  }
  console.log(`TOTAL ${total} (680 ops across ${mainCatalog.files.length} manifest files)`);

  console.log(`\n=== pinned ===`);
  reportPinned('main catalog', mainCatalog);
  reportPinned('bootstrap project catalog', bootstrap);
}

main();
