/**
 * Shared AWS service taxonomy — the single source of truth both AWS catalog
 * generators consume (gen-aws-service-tiles.mjs and gen-aws-tag-catalog.mjs).
 *
 * This is the AWS analog of catalog/azure-capability-ledger.json: the Azure tag
 * catalog took each type's `family` from the ledger; AWS has no ledger, so this
 * module classifies each aws_* resource type into its portal SERVICE (for the
 * tile map) and its FAMILY (for the comprehensive-tag manifest split) by the
 * resource-type prefix — which, for AWS, IS the service name in the
 * overwhelming majority of cases (aws_<service>_<resource>).
 *
 * classify() is deterministic and total: a curated SERVICES rule when one
 * matches (longest prefix wins → aws_cloudwatch_event_* beats aws_cloudwatch_*),
 * otherwise a prefix-derived fallback so NO type is ever left unmapped.
 */

// [prefix, slug, displayName, category]. Longest matching prefix wins.
export const SERVICES = [
  // ── Compute ────────────────────────────────────────────────────────────
  ['aws_instance', 'ec2', 'EC2', 'Compute'],
  ['aws_ami', 'ec2', 'EC2', 'Compute'],
  ['aws_key_pair', 'ec2', 'EC2', 'Compute'],
  ['aws_placement_group', 'ec2', 'EC2', 'Compute'],
  ['aws_launch_template', 'ec2', 'EC2', 'Compute'],
  ['aws_launch_configuration', 'ec2', 'EC2', 'Compute'],
  ['aws_spot', 'ec2', 'EC2', 'Compute'],
  ['aws_ec2_host', 'ec2', 'EC2', 'Compute'],
  ['aws_ec2_capacity', 'ec2', 'EC2', 'Compute'],
  ['aws_ec2_fleet', 'ec2', 'EC2', 'Compute'],
  ['aws_ec2_serial', 'ec2', 'EC2', 'Compute'],
  ['aws_ec2_image', 'ec2', 'EC2', 'Compute'],
  ['aws_autoscaling', 'autoscaling', 'EC2 Auto Scaling', 'Compute'],
  ['aws_appautoscaling', 'application-autoscaling', 'Application Auto Scaling', 'Compute'],
  ['aws_lambda', 'lambda', 'Lambda', 'Compute'],
  ['aws_batch', 'batch', 'Batch', 'Compute'],
  ['aws_lightsail', 'lightsail', 'Lightsail', 'Compute'],
  ['aws_serverlessapplicationrepository', 'serverlessrepo', 'Serverless Application Repository', 'Compute'],
  ['aws_apprunner', 'apprunner', 'App Runner', 'Compute'],
  ['aws_imagebuilder', 'imagebuilder', 'EC2 Image Builder', 'Compute'],
  ['aws_outposts', 'outposts', 'Outposts', 'Compute'],
  ['aws_elastic_beanstalk', 'elastic-beanstalk', 'Elastic Beanstalk', 'Compute'],
  ['aws_elasticbeanstalk', 'elastic-beanstalk', 'Elastic Beanstalk', 'Compute'],
  ['aws_evs', 'elastic-vmware', 'Elastic VMware Service', 'Compute'],
  // ── Containers ─────────────────────────────────────────────────────────
  ['aws_ecs', 'ecs', 'ECS', 'Containers'],
  ['aws_eks', 'eks', 'EKS', 'Containers'],
  ['aws_ecr', 'ecr', 'ECR', 'Containers'],
  ['aws_ecrpublic', 'ecr', 'ECR', 'Containers'],
  // ── Storage ────────────────────────────────────────────────────────────
  ['aws_ebs', 'ebs', 'EBS', 'Storage'],
  ['aws_volume_attachment', 'ebs', 'EBS', 'Storage'],
  ['aws_snapshot', 'ebs', 'EBS', 'Storage'],
  ['aws_s3control', 's3', 'S3', 'Storage'],
  ['aws_s3outposts', 's3', 'S3', 'Storage'],
  ['aws_s3tables', 's3-tables', 'S3 Tables', 'Storage'],
  ['aws_s3_', 's3', 'S3', 'Storage'],
  ['aws_efs', 'efs', 'EFS', 'Storage'],
  ['aws_fsx', 'fsx', 'FSx', 'Storage'],
  ['aws_backup', 'backup', 'AWS Backup', 'Storage'],
  ['aws_storagegateway', 'storage-gateway', 'Storage Gateway', 'Storage'],
  ['aws_glacier', 'glacier', 'S3 Glacier', 'Storage'],
  ['aws_dlm', 'dlm', 'Data Lifecycle Manager', 'Storage'],
  // ── Database ───────────────────────────────────────────────────────────
  ['aws_db', 'rds', 'RDS', 'Database'],
  ['aws_rds', 'rds', 'RDS', 'Database'],
  ['aws_dynamodb', 'dynamodb', 'DynamoDB', 'Database'],
  ['aws_dax', 'dax', 'DynamoDB Accelerator', 'Database'],
  ['aws_elasticache', 'elasticache', 'ElastiCache', 'Database'],
  ['aws_memorydb', 'memorydb', 'MemoryDB', 'Database'],
  ['aws_neptune', 'neptune', 'Neptune', 'Database'],
  ['aws_docdb', 'documentdb', 'DocumentDB', 'Database'],
  ['aws_docdbelastic', 'documentdb', 'DocumentDB', 'Database'],
  ['aws_redshiftserverless', 'redshift-serverless', 'Redshift Serverless', 'Database'],
  ['aws_redshift', 'redshift', 'Redshift', 'Database'],
  ['aws_timestreaminfluxdb', 'timestream-influxdb', 'Timestream for InfluxDB', 'Database'],
  ['aws_timestreamwrite', 'timestream', 'Timestream', 'Database'],
  ['aws_timestreamquery', 'timestream', 'Timestream', 'Database'],
  ['aws_timestream', 'timestream', 'Timestream', 'Database'],
  ['aws_qldb', 'qldb', 'QLDB', 'Database'],
  ['aws_keyspaces', 'keyspaces', 'Keyspaces', 'Database'],
  // ── Networking & Content Delivery ──────────────────────────────────────
  ['aws_vpc_security_group', 'security-groups', 'Security Groups', 'Networking & Content Delivery'],
  ['aws_default_security_group', 'security-groups', 'Security Groups', 'Networking & Content Delivery'],
  ['aws_security_group', 'security-groups', 'Security Groups', 'Networking & Content Delivery'],
  ['aws_default_route_table', 'routing', 'Routing', 'Networking & Content Delivery'],
  ['aws_main_route_table', 'routing', 'Routing', 'Networking & Content Delivery'],
  ['aws_route_table', 'routing', 'Routing', 'Networking & Content Delivery'],
  ['aws_route', 'routing', 'Routing', 'Networking & Content Delivery'],
  ['aws_vpc', 'vpc', 'VPC', 'Networking & Content Delivery'],
  ['aws_subnet', 'vpc', 'VPC', 'Networking & Content Delivery'],
  ['aws_eip', 'vpc', 'VPC', 'Networking & Content Delivery'],
  ['aws_internet_gateway', 'vpc', 'VPC', 'Networking & Content Delivery'],
  ['aws_egress_only_internet_gateway', 'vpc', 'VPC', 'Networking & Content Delivery'],
  ['aws_nat_gateway', 'vpc', 'VPC', 'Networking & Content Delivery'],
  ['aws_network_acl', 'vpc', 'VPC', 'Networking & Content Delivery'],
  ['aws_default_network_acl', 'vpc', 'VPC', 'Networking & Content Delivery'],
  ['aws_default_vpc', 'vpc', 'VPC', 'Networking & Content Delivery'],
  ['aws_default_subnet', 'vpc', 'VPC', 'Networking & Content Delivery'],
  ['aws_flow_log', 'vpc', 'VPC', 'Networking & Content Delivery'],
  ['aws_network_interface', 'vpc', 'VPC', 'Networking & Content Delivery'],
  ['aws_prefix_list', 'vpc', 'VPC', 'Networking & Content Delivery'],
  ['aws_ec2_managed_prefix_list', 'vpc', 'VPC', 'Networking & Content Delivery'],
  ['aws_ec2_transit_gateway', 'transit-gateway', 'Transit Gateway', 'Networking & Content Delivery'],
  ['aws_ec2_client_vpn', 'client-vpn', 'Client VPN', 'Networking & Content Delivery'],
  ['aws_lb', 'alb', 'Load Balancing', 'Networking & Content Delivery'],
  ['aws_alb', 'alb', 'Load Balancing', 'Networking & Content Delivery'],
  ['aws_elb', 'elb-classic', 'Classic Load Balancer', 'Networking & Content Delivery'],
  ['aws_app_cookie', 'elb-classic', 'Classic Load Balancer', 'Networking & Content Delivery'],
  ['aws_lb_cookie', 'elb-classic', 'Classic Load Balancer', 'Networking & Content Delivery'],
  ['aws_route53resolver', 'route53-resolver', 'Route 53 Resolver', 'Networking & Content Delivery'],
  ['aws_route53recoverycontrolconfig', 'route53-arc', 'Route 53 ARC', 'Networking & Content Delivery'],
  ['aws_route53recoveryreadiness', 'route53-arc', 'Route 53 ARC', 'Networking & Content Delivery'],
  ['aws_route53domains', 'route53-domains', 'Route 53 Domains', 'Networking & Content Delivery'],
  ['aws_route53profiles', 'route53-profiles', 'Route 53 Profiles', 'Networking & Content Delivery'],
  ['aws_route53', 'route53', 'Route 53', 'Networking & Content Delivery'],
  ['aws_cloudfrontkeyvaluestore', 'cloudfront', 'CloudFront', 'Networking & Content Delivery'],
  ['aws_cloudfront', 'cloudfront', 'CloudFront', 'Networking & Content Delivery'],
  ['aws_globalaccelerator', 'global-accelerator', 'Global Accelerator', 'Networking & Content Delivery'],
  ['aws_apigatewayv2', 'api-gateway', 'API Gateway', 'Networking & Content Delivery'],
  ['aws_api_gateway', 'api-gateway', 'API Gateway', 'Networking & Content Delivery'],
  ['aws_apigateway', 'api-gateway', 'API Gateway', 'Networking & Content Delivery'],
  ['aws_customer_gateway', 'vpn', 'Site-to-Site VPN', 'Networking & Content Delivery'],
  ['aws_vpn', 'vpn', 'Site-to-Site VPN', 'Networking & Content Delivery'],
  ['aws_dx', 'direct-connect', 'Direct Connect', 'Networking & Content Delivery'],
  ['aws_networkmanager', 'network-manager', 'Cloud WAN', 'Networking & Content Delivery'],
  ['aws_networkfirewall', 'network-firewall', 'Network Firewall', 'Networking & Content Delivery'],
  ['aws_network_firewall', 'network-firewall', 'Network Firewall', 'Networking & Content Delivery'],
  ['aws_vpclattice', 'vpc-lattice', 'VPC Lattice', 'Networking & Content Delivery'],
  ['aws_servicediscovery', 'cloud-map', 'Cloud Map', 'Networking & Content Delivery'],
  ['aws_service_discovery', 'cloud-map', 'Cloud Map', 'Networking & Content Delivery'],
  // ── Analytics ──────────────────────────────────────────────────────────
  ['aws_glue', 'glue', 'Glue', 'Analytics'],
  ['aws_athena', 'athena', 'Athena', 'Analytics'],
  ['aws_kinesisanalyticsv2', 'kinesis-analytics', 'Managed Service for Apache Flink', 'Analytics'],
  ['aws_kinesis_analytics', 'kinesis-analytics', 'Managed Service for Apache Flink', 'Analytics'],
  ['aws_kinesis_video', 'kinesis-video', 'Kinesis Video Streams', 'Analytics'],
  ['aws_kinesis_firehose', 'firehose', 'Data Firehose', 'Analytics'],
  ['aws_kinesis', 'kinesis', 'Kinesis Data Streams', 'Analytics'],
  ['aws_firehose', 'firehose', 'Data Firehose', 'Analytics'],
  ['aws_emrserverless', 'emr-serverless', 'EMR Serverless', 'Analytics'],
  ['aws_emrcontainers', 'emr-containers', 'EMR on EKS', 'Analytics'],
  ['aws_emr', 'emr', 'EMR', 'Analytics'],
  ['aws_mskconnect', 'msk', 'Managed Streaming for Kafka', 'Analytics'],
  ['aws_msk', 'msk', 'Managed Streaming for Kafka', 'Analytics'],
  ['aws_opensearchserverless', 'opensearch-serverless', 'OpenSearch Serverless', 'Analytics'],
  ['aws_opensearch', 'opensearch', 'OpenSearch Service', 'Analytics'],
  ['aws_elasticsearch', 'opensearch', 'OpenSearch Service', 'Analytics'],
  ['aws_quicksight', 'quicksight', 'QuickSight', 'Analytics'],
  ['aws_datazone', 'datazone', 'DataZone', 'Analytics'],
  ['aws_datapipeline', 'data-pipeline', 'Data Pipeline', 'Analytics'],
  ['aws_data_pipeline', 'data-pipeline', 'Data Pipeline', 'Analytics'],
  ['aws_cloudsearch', 'cloudsearch', 'CloudSearch', 'Analytics'],
  ['aws_lakeformation', 'lake-formation', 'Lake Formation', 'Analytics'],
  ['aws_finspace', 'finspace', 'FinSpace', 'Analytics'],
  ['aws_dataexchange', 'data-exchange', 'Data Exchange', 'Analytics'],
  ['aws_simpledb', 'simpledb', 'SimpleDB', 'Database'],
  ['aws_sdb', 'simpledb', 'SimpleDB', 'Database'],
  ['aws_appmesh', 'app-mesh', 'App Mesh', 'Networking & Content Delivery'],
  ['aws_elastictranscoder', 'elastic-transcoder', 'Elastic Transcoder', 'Media Services'],
  ['aws_elastic_transcoder', 'elastic-transcoder', 'Elastic Transcoder', 'Media Services'],
  // ── Machine Learning ───────────────────────────────────────────────────
  ['aws_sagemaker', 'sagemaker', 'SageMaker', 'Machine Learning'],
  ['aws_bedrockagent', 'bedrock', 'Bedrock', 'Machine Learning'],
  ['aws_bedrock', 'bedrock', 'Bedrock', 'Machine Learning'],
  ['aws_comprehend', 'comprehend', 'Comprehend', 'Machine Learning'],
  ['aws_rekognition', 'rekognition', 'Rekognition', 'Machine Learning'],
  ['aws_lexv2models', 'lex', 'Lex', 'Machine Learning'],
  ['aws_lex', 'lex', 'Lex', 'Machine Learning'],
  ['aws_polly', 'polly', 'Polly', 'Machine Learning'],
  ['aws_transcribe', 'transcribe', 'Transcribe', 'Machine Learning'],
  ['aws_translate', 'translate', 'Translate', 'Machine Learning'],
  ['aws_personalize', 'personalize', 'Personalize', 'Machine Learning'],
  ['aws_forecast', 'forecast', 'Forecast', 'Machine Learning'],
  ['aws_kendra', 'kendra', 'Kendra', 'Machine Learning'],
  ['aws_frauddetector', 'fraud-detector', 'Fraud Detector', 'Machine Learning'],
  // ── Application Integration ────────────────────────────────────────────
  ['aws_sns', 'sns', 'SNS', 'Application Integration'],
  ['aws_sqs', 'sqs', 'SQS', 'Application Integration'],
  ['aws_cloudwatch_event', 'eventbridge', 'EventBridge', 'Application Integration'],
  ['aws_schemas', 'eventbridge', 'EventBridge', 'Application Integration'],
  ['aws_pipes', 'eventbridge-pipes', 'EventBridge Pipes', 'Application Integration'],
  ['aws_scheduler', 'eventbridge-scheduler', 'EventBridge Scheduler', 'Application Integration'],
  ['aws_sfn', 'step-functions', 'Step Functions', 'Application Integration'],
  ['aws_mq', 'mq', 'Amazon MQ', 'Application Integration'],
  ['aws_mwaa', 'mwaa', 'Managed Workflows for Apache Airflow', 'Application Integration'],
  ['aws_appflow', 'appflow', 'AppFlow', 'Application Integration'],
  ['aws_appsync', 'appsync', 'AppSync', 'Application Integration'],
  ['aws_swf', 'swf', 'Simple Workflow Service', 'Application Integration'],
  ['aws_appintegrations', 'app-integrations', 'AppIntegrations', 'Application Integration'],
  ['aws_appconfig', 'appconfig', 'AppConfig', 'Application Integration'],
  // ── Machine Learning / Media / IoT / Migration / DevTools / Mgmt / etc ──
  ['aws_media_convert', 'mediaconvert', 'MediaConvert', 'Media Services'],
  ['aws_mediaconvert', 'mediaconvert', 'MediaConvert', 'Media Services'],
  ['aws_media_live', 'medialive', 'MediaLive', 'Media Services'],
  ['aws_medialive', 'medialive', 'MediaLive', 'Media Services'],
  ['aws_media_package', 'mediapackage', 'MediaPackage', 'Media Services'],
  ['aws_mediapackage', 'mediapackage', 'MediaPackage', 'Media Services'],
  ['aws_media_store', 'mediastore', 'MediaStore', 'Media Services'],
  ['aws_mediastore', 'mediastore', 'MediaStore', 'Media Services'],
  ['aws_mediaconnect', 'mediaconnect', 'MediaConnect', 'Media Services'],
  ['aws_ivschat', 'ivs', 'Interactive Video Service', 'Media Services'],
  ['aws_ivs', 'ivs', 'Interactive Video Service', 'Media Services'],
  ['aws_iotanalytics', 'iot-analytics', 'IoT Analytics', 'Internet of Things'],
  ['aws_iotevents', 'iot-events', 'IoT Events', 'Internet of Things'],
  ['aws_iotwireless', 'iot-wireless', 'IoT Wireless', 'Internet of Things'],
  ['aws_iotfleethub', 'iot-fleethub', 'IoT Fleet Hub', 'Internet of Things'],
  ['aws_iottwinmaker', 'iot-twinmaker', 'IoT TwinMaker', 'Internet of Things'],
  ['aws_iot', 'iot-core', 'IoT Core', 'Internet of Things'],
  ['aws_greengrass', 'greengrass', 'IoT Greengrass', 'Internet of Things'],
  ['aws_dms', 'dms', 'Database Migration Service', 'Migration & Transfer'],
  ['aws_transfer', 'transfer', 'Transfer Family', 'Migration & Transfer'],
  ['aws_datasync', 'datasync', 'DataSync', 'Migration & Transfer'],
  ['aws_migrationhub', 'migration-hub', 'Migration Hub', 'Migration & Transfer'],
  ['aws_mgn', 'mgn', 'Application Migration Service', 'Migration & Transfer'],
  ['aws_drs', 'drs', 'Elastic Disaster Recovery', 'Migration & Transfer'],
  ['aws_snowball', 'snow-family', 'Snow Family', 'Migration & Transfer'],
  ['aws_codebuild', 'codebuild', 'CodeBuild', 'Developer Tools'],
  ['aws_codecommit', 'codecommit', 'CodeCommit', 'Developer Tools'],
  ['aws_codedeploy', 'codedeploy', 'CodeDeploy', 'Developer Tools'],
  ['aws_codepipeline', 'codepipeline', 'CodePipeline', 'Developer Tools'],
  ['aws_codeartifact', 'codeartifact', 'CodeArtifact', 'Developer Tools'],
  ['aws_codestarconnections', 'codeconnections', 'CodeConnections', 'Developer Tools'],
  ['aws_codestarnotifications', 'codestar-notifications', 'CodeStar Notifications', 'Developer Tools'],
  ['aws_codestar', 'codestar', 'CodeStar', 'Developer Tools'],
  ['aws_codeconnections', 'codeconnections', 'CodeConnections', 'Developer Tools'],
  ['aws_codecatalyst', 'codecatalyst', 'CodeCatalyst', 'Developer Tools'],
  ['aws_codeguruprofiler', 'codeguru', 'CodeGuru', 'Developer Tools'],
  ['aws_codegurureviewer', 'codeguru', 'CodeGuru', 'Developer Tools'],
  ['aws_cloud9', 'cloud9', 'Cloud9', 'Developer Tools'],
  ['aws_xray', 'xray', 'X-Ray', 'Developer Tools'],
  ['aws_evidently', 'cloudwatch-evidently', 'CloudWatch Evidently', 'Developer Tools'],
  // ── Management & Governance ────────────────────────────────────────────
  ['aws_cloudwatch_log', 'cloudwatch', 'CloudWatch', 'Management & Governance'],
  ['aws_cloudwatch', 'cloudwatch', 'CloudWatch', 'Management & Governance'],
  ['aws_rum', 'cloudwatch-rum', 'CloudWatch RUM', 'Management & Governance'],
  ['aws_synthetics', 'cloudwatch-synthetics', 'CloudWatch Synthetics', 'Management & Governance'],
  ['aws_oam', 'cloudwatch', 'CloudWatch', 'Management & Governance'],
  ['aws_cloudtrail', 'cloudtrail', 'CloudTrail', 'Management & Governance'],
  ['aws_config', 'config', 'Config', 'Management & Governance'],
  ['aws_ssmcontacts', 'ssm-incident-manager', 'SSM Incident Manager', 'Management & Governance'],
  ['aws_ssmincidents', 'ssm-incident-manager', 'SSM Incident Manager', 'Management & Governance'],
  ['aws_ssmquicksetup', 'ssm', 'Systems Manager', 'Management & Governance'],
  ['aws_ssm', 'ssm', 'Systems Manager', 'Management & Governance'],
  ['aws_cloudformation', 'cloudformation', 'CloudFormation', 'Management & Governance'],
  ['aws_servicecatalogappregistry', 'service-catalog', 'Service Catalog', 'Management & Governance'],
  ['aws_servicecatalog', 'service-catalog', 'Service Catalog', 'Management & Governance'],
  ['aws_servicequotas', 'service-quotas', 'Service Quotas', 'Management & Governance'],
  ['aws_licensemanager', 'licensemanager', 'License Manager', 'Management & Governance'],
  ['aws_resourcegroups', 'resource-groups', 'Resource Groups', 'Management & Governance'],
  ['aws_resourceexplorer2', 'resource-explorer', 'Resource Explorer', 'Management & Governance'],
  ['aws_grafana', 'managed-grafana', 'Managed Grafana', 'Management & Governance'],
  ['aws_prometheus', 'managed-prometheus', 'Managed Prometheus', 'Management & Governance'],
  ['aws_controltower', 'control-tower', 'Control Tower', 'Management & Governance'],
  ['aws_chatbot', 'chatbot', 'Chatbot', 'Management & Governance'],
  ['aws_autoscalingplans', 'autoscaling-plans', 'AWS Auto Scaling', 'Management & Governance'],
  ['aws_ce_', 'cost-explorer', 'Cost Explorer', 'Cost Management'],
  ['aws_costoptimizationhub', 'cost-optimization-hub', 'Cost Optimization Hub', 'Cost Management'],
  ['aws_bcmdataexports', 'billing', 'Billing & Cost Management', 'Cost Management'],
  // ── Security, Identity & Compliance ────────────────────────────────────
  ['aws_iam_', 'iam', 'IAM', 'Security, Identity & Compliance'],
  ['aws_kms', 'kms', 'KMS', 'Security, Identity & Compliance'],
  ['aws_acmpca', 'acm-pca', 'Private Certificate Authority', 'Security, Identity & Compliance'],
  ['aws_acm', 'acm', 'Certificate Manager', 'Security, Identity & Compliance'],
  ['aws_secretsmanager', 'secretsmanager', 'Secrets Manager', 'Security, Identity & Compliance'],
  ['aws_wafv2', 'waf', 'WAF', 'Security, Identity & Compliance'],
  ['aws_wafregional', 'waf', 'WAF', 'Security, Identity & Compliance'],
  ['aws_waf', 'waf', 'WAF', 'Security, Identity & Compliance'],
  ['aws_shield', 'shield', 'Shield', 'Security, Identity & Compliance'],
  ['aws_guardduty', 'guardduty', 'GuardDuty', 'Security, Identity & Compliance'],
  ['aws_securityhub', 'securityhub', 'Security Hub', 'Security, Identity & Compliance'],
  ['aws_inspector2', 'inspector', 'Inspector', 'Security, Identity & Compliance'],
  ['aws_inspector', 'inspector', 'Inspector', 'Security, Identity & Compliance'],
  ['aws_macie2', 'macie', 'Macie', 'Security, Identity & Compliance'],
  ['aws_macie', 'macie', 'Macie', 'Security, Identity & Compliance'],
  ['aws_detective', 'detective', 'Detective', 'Security, Identity & Compliance'],
  ['aws_cognito', 'cognito', 'Cognito', 'Security, Identity & Compliance'],
  ['aws_organizations', 'organizations', 'Organizations', 'Security, Identity & Compliance'],
  ['aws_ssoadmin', 'iam-identity-center', 'IAM Identity Center', 'Security, Identity & Compliance'],
  ['aws_identitystore', 'iam-identity-center', 'IAM Identity Center', 'Security, Identity & Compliance'],
  ['aws_directory_service', 'directory-service', 'Directory Service', 'Security, Identity & Compliance'],
  ['aws_ds_', 'directory-service', 'Directory Service', 'Security, Identity & Compliance'],
  ['aws_ram_', 'ram', 'Resource Access Manager', 'Security, Identity & Compliance'],
  ['aws_accessanalyzer', 'access-analyzer', 'IAM Access Analyzer', 'Security, Identity & Compliance'],
  ['aws_securitylake', 'security-lake', 'Security Lake', 'Security, Identity & Compliance'],
  ['aws_signer', 'signer', 'Signer', 'Security, Identity & Compliance'],
  ['aws_rolesanywhere', 'iam-roles-anywhere', 'IAM Roles Anywhere', 'Security, Identity & Compliance'],
  ['aws_cloudhsm', 'cloudhsm', 'CloudHSM', 'Security, Identity & Compliance'],
  ['aws_fms', 'firewall-manager', 'Firewall Manager', 'Security, Identity & Compliance'],
  ['aws_verifiedaccess', 'verified-access', 'Verified Access', 'Security, Identity & Compliance'],
  ['aws_verifiedpermissions', 'verified-permissions', 'Verified Permissions', 'Security, Identity & Compliance'],
  ['aws_paymentcryptography', 'payment-cryptography', 'Payment Cryptography', 'Security, Identity & Compliance'],
  // ── Business Applications / Front-End / End User / niche ───────────────
  ['aws_connect', 'connect', 'Connect', 'Business Applications'],
  ['aws_chimesdkvoice', 'chime', 'Chime', 'Business Applications'],
  ['aws_chimesdkmediapipelines', 'chime', 'Chime', 'Business Applications'],
  ['aws_chime', 'chime', 'Chime', 'Business Applications'],
  ['aws_sesv2', 'ses', 'Simple Email Service', 'Business Applications'],
  ['aws_ses', 'ses', 'Simple Email Service', 'Business Applications'],
  ['aws_wisdom', 'wisdom', 'Wisdom', 'Business Applications'],
  ['aws_workmail', 'workmail', 'WorkMail', 'Business Applications'],
  ['aws_qbusiness', 'amazon-q-business', 'Amazon Q Business', 'Business Applications'],
  ['aws_supplychain', 'supply-chain', 'Supply Chain', 'Business Applications'],
  ['aws_pinpoint', 'pinpoint', 'Pinpoint', 'Front-End Web & Mobile'],
  ['aws_amplify', 'amplify', 'Amplify', 'Front-End Web & Mobile'],
  ['aws_location', 'location', 'Location Service', 'Front-End Web & Mobile'],
  ['aws_devicefarm', 'device-farm', 'Device Farm', 'Front-End Web & Mobile'],
  ['aws_appintegrations_', 'app-integrations', 'AppIntegrations', 'Application Integration'],
  ['aws_workspacesweb', 'workspaces-web', 'WorkSpaces Web', 'End User Computing'],
  ['aws_workspaces', 'workspaces', 'WorkSpaces', 'End User Computing'],
  ['aws_appstream', 'appstream', 'AppStream 2.0', 'End User Computing'],
  ['aws_worklink', 'worklink', 'WorkLink', 'End User Computing'],
  ['aws_managedblockchain', 'managed-blockchain', 'Managed Blockchain', 'Blockchain'],
  ['aws_groundstation', 'ground-station', 'Ground Station', 'Satellite'],
  ['aws_gamelift', 'gamelift', 'GameLift', 'Game Tech'],
];

/** portal category → comprehensive-tag manifest family (aws-<family>.json). */
export const CATEGORY_FAMILY = {
  Compute: 'compute',
  Containers: 'containers',
  Storage: 'storage',
  Database: 'database',
  'Networking & Content Delivery': 'networking',
  Analytics: 'analytics',
  'Machine Learning': 'ml',
  'Application Integration': 'integration',
  'Security, Identity & Compliance': 'security',
  'Management & Governance': 'management',
  'Cost Management': 'management',
  'Developer Tools': 'devtools',
  'Migration & Transfer': 'migration',
  'Media Services': 'media',
  'Internet of Things': 'iot',
  'End User Computing': 'enduser',
  'Front-End Web & Mobile': 'webmobile',
  'Business Applications': 'business',
  Blockchain: 'other',
  Satellite: 'other',
  'Game Tech': 'other',
  'Other AWS Services': 'other',
};

/** Human-readable family label for the manifest summary line. */
export const FAMILY_LABEL = {
  compute: 'Compute',
  containers: 'Containers',
  storage: 'Storage',
  database: 'Database',
  networking: 'Networking',
  analytics: 'Analytics',
  ml: 'Machine Learning',
  integration: 'Application Integration',
  management: 'Management & Governance',
  devtools: 'Developer Tools',
  migration: 'Migration & Transfer',
  media: 'Media Services',
  iot: 'Internet of Things',
  enduser: 'End User Computing',
  webmobile: 'Front-End Web & Mobile',
  business: 'Business Applications',
  other: 'Other AWS Resources',
};

/** Classify an aws_* type → its named service. Deterministic and total:
 * curated rule (longest prefix wins) or a prefix-derived fallback. */
export function classify(type) {
  let best = null;
  for (const [prefix, slug, name, cat] of SERVICES) {
    if (type === prefix || type.startsWith(prefix + '_') || type.startsWith(prefix)) {
      if (!best || prefix.length > best[0].length) best = [prefix, slug, name, cat];
    }
  }
  if (best) return { slug: best[1], name: best[2], category: best[3] };
  // Fallback: the leading segment IS the AWS service in almost every case.
  // Short lowercase prefixes are almost always acronyms (mq, ses, dax) → upper.
  const short = type.replace(/^aws_/, '');
  const seg = short.split('_')[0] || short;
  const name = seg.length <= 4 ? seg.toUpperCase() : seg.charAt(0).toUpperCase() + seg.slice(1);
  return { slug: seg.replace(/[^a-z0-9]+/g, '-'), name, category: 'Other AWS Services' };
}

/** The comprehensive-tag manifest family for a type (aws-<family>.json). */
export function familyOf(type) {
  return CATEGORY_FAMILY[classify(type).category] ?? 'other';
}
