#!/usr/bin/env python3
"""gen-imports.py — discovery manifest -> imports.tf (Terraform import blocks).

Mirrors the conventions of the prod import archive (importer/prod/imports.tf)
exactly:
  - one `import { to = <type>.<label>  id = "<live-id>" }` block per resource
    (two-space indent, id always quoted — the archive's shape)
  - blocks sorted by (type, label): the original 1,733-block generation was
    address-sorted; only later reconciliation appends broke the global order
  - a banner header carrying account/region/provenance, like the archive's
  - non-default-region resources use the provider's `<id>@<region>` import id
    (the archive's ap-southeast-1 DR resources, e.g. "vpc-...@ap-southeast-1"),
    via --id-region-suffix

The output is NOT runnable from importer/ — like the archive, import blocks
must sit in the SAME root as the resource definitions they target. The runbook
step this feeds (docs/runbooks/new-env-import.md phase 3): copy imports.tf
into environments/<env>/ and run
    terraform plan -generate-config-out=generated.tf

Refusals (never a silent skip):
  - a resource row missing type/id/label          -> REFUSE MALFORMED_ROW
  - a label that is not a valid HCL identifier    -> REFUSE BAD_LABEL
  - two rows landing on the same address          -> REFUSE DUPLICATE_ADDRESS
Rows whose disposition is not "import" are excluded and COUNTED on stdout
(replace/deprecate/ignore are the discovery-guide §4 dispositions — they are
decisions, not omissions).

Stdlib only. Deterministic: same manifest in, byte-identical imports.tf out.
Exit codes: 0 ok · 2 refusal.
"""
import argparse
import hashlib
import json
import re
import sys

LABEL_RE = re.compile(r"^[a-z_][a-z0-9_]*$")


def refuse(code, msg):
    print(f"REFUSE {code}: {msg}", file=sys.stderr)
    sys.exit(2)


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--manifest", required=True, help="discovery-manifest.json from discover.py build")
    p.add_argument("--out", required=True, help="imports.tf to write")
    p.add_argument("--phase", type=int, default=0,
                   help="emit only this strategy.md phase (2/3/4/5); default all — "
                        "use per-phase batches to honor strategy.md's small-batches rule")
    p.add_argument("--id-region-suffix", default="",
                   help="append @<region> to non-ARN ids (resources captured in a region "
                        "other than the root's default provider region)")
    args = p.parse_args(argv)

    try:
        with open(args.manifest) as fh:
            manifest = json.load(fh)
    except (OSError, json.JSONDecodeError) as e:
        refuse("BAD_MANIFEST", f"cannot read {args.manifest}: {e}")

    rows = manifest.get("resources", [])
    if not isinstance(rows, list):
        refuse("BAD_MANIFEST", "manifest.resources is not a list")

    excluded = {}
    selected = []
    for i, row in enumerate(rows):
        for key in ("type", "id", "label"):
            if not isinstance(row.get(key), str) or not row[key]:
                refuse("MALFORMED_ROW", f"resources[{i}] is missing '{key}' — refusing rather than dropping it")
        disp = row.get("disposition", "import")
        if disp != "import":
            excluded[disp] = excluded.get(disp, 0) + 1
            continue
        if args.phase and row.get("phase") != args.phase:
            continue
        if not LABEL_RE.match(row["label"]):
            refuse("BAD_LABEL", f"{row['type']} label {row['label']!r} is not a valid HCL identifier — "
                                "curate it in the manifest and re-run")
        selected.append(row)

    selected.sort(key=lambda r: (r["type"], r["label"]))
    seen = set()
    for row in selected:
        addr = f"{row['type']}.{row['label']}"
        if addr in seen:
            refuse("DUPLICATE_ADDRESS", f"two resources map to {addr} — fix labels in the manifest")
        seen.add(addr)

    manifest_sha = hashlib.sha256(open(args.manifest, "rb").read()).hexdigest()
    account = manifest.get("account", "unknown")
    region = manifest.get("region", "unknown")
    captured = manifest.get("capturedAt", "unknown")
    phase_note = f" (phase {args.phase} only)" if args.phase else ""

    lines = [
        "# " + "─" * 77,
        f"# IMPORT MAP — generated by importer/kit/gen-imports.py, NOT YET APPLIED{phase_note}.",
        "#",
        f"# Account {account}, region {region}. Discovery captured {captured}.",
        f"# Source manifest sha256: {manifest_sha}",
        f"# {len(selected)} import block(s). Read-only capture; applying these blocks only",
        "# writes STATE (import never mutates live resources).",
        "#",
        "# Not runnable from importer/ — import blocks must sit in the same root as the",
        "# resource definitions they target (see importer/README.md). Next step:",
        "#   copy into environments/<env>/ then: terraform plan -generate-config-out=generated.tf",
        "# " + "─" * 77,
        "",
    ]
    for row in selected:
        rid = row["id"]
        if args.id_region_suffix and not rid.startswith("arn:"):
            rid = f"{rid}@{args.id_region_suffix}"
        lines.append("import {")
        lines.append(f"  to = {row['type']}.{row['label']}")
        lines.append(f'  id = "{rid}"')
        lines.append("}")
        lines.append("")

    with open(args.out, "w") as fh:
        fh.write("\n".join(lines))

    print(f"WROTE {len(selected)} import block(s) to {args.out}{phase_note}")
    for disp in sorted(excluded):
        print(f"  excluded {excluded[disp]} row(s) with disposition '{disp}' (deliberate, per manifest)")
    print("next: copy into environments/<env>/ then run\n"
          "  terraform plan -generate-config-out=generated.tf\n"
          "(docs/runbooks/new-env-import.md, phase 3)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
